
-- _/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/_/
-- creating index after loading large data for performance 
-- _/_/_/_/_/_/_/_/_/_/

--
-- GIANT foreign key
--
alter table GIANT add constraint FK_GIANT_SELF
	foreign key (SELF_PARENT_ID) references GIANT (GIANT_ID) ;

alter table GIANT add constraint FK_GIANT_GIANT_STATUS
	foreign key (GIANT_STATUS_CODE) references GIANT_STATUS (GIANT_STATUS_CODE) ;

alter table GIANT add constraint FK_GIANT_ZONE_MEMBER
	foreign key (ZONE_MEMBER_ID) references MEMBER (MEMBER_ID) ;

alter table GIANT add constraint FK_GIANT_ZONE_PURCHASE
	foreign key (ZONE_PURCHASE_ID) references PURCHASE (PURCHASE_ID) ;

alter table GIANT add constraint FK_GIANT_ZONE_PRODUCT
	foreign key (ZONE_PRODUCT_ID) references PRODUCT (PRODUCT_ID) ;


--
-- GIANT_REF foreign key
--
alter table GIANT_REF add constraint FK_GIANT_REF_GIANT
	foreign key (GIANT_ID) references GIANT (GIANT_ID) ;

alter table GIANT_REF add constraint FK_GIANT_REF_GIANT_STATUS
	foreign key (GIANT_STATUS_CODE) references GIANT_STATUS (GIANT_STATUS_CODE) ;

alter table GIANT_REF add constraint FK_GIANT_REF_SELF
	foreign key (SELF_PARENT_ID) references GIANT_REF (GIANT_REF_ID) ;

alter table GIANT_REF add constraint FK_GIANT_REF_ZONE_MEMBER
	foreign key (ZONE_MEMBER_ID) references MEMBER (MEMBER_ID) ;

alter table GIANT_REF add constraint FK_GIANT_REF_ZONE_PURCHASE
	foreign key (ZONE_PURCHASE_ID) references PURCHASE (PURCHASE_ID) ;

alter table GIANT_REF add constraint FK_GIANT_REF_ZONE_PRODUCT
	foreign key (ZONE_PRODUCT_ID) references PRODUCT (PRODUCT_ID) ;


--
-- GIANT_SIDE foreign key
--
alter table GIANT_SIDE add constraint FK_GIANT_SIDE_GIANT
	foreign key (GIANT_ID) references GIANT (GIANT_ID) ;

alter table GIANT_SIDE add constraint FK_GIANT_SIDE_SELF
	foreign key (SELF_PARENT_ID) references GIANT_SIDE (GIANT_SIDE_ID) ;

alter table GIANT_SIDE add constraint FK_GIANT_SIDE_GIANT_STATUS
	foreign key (GIANT_STATUS_CODE) references GIANT_STATUS (GIANT_STATUS_CODE) ;

alter table GIANT_SIDE add constraint FK_GIANT_SIDE_ZONE_MEMBER
	foreign key (ZONE_MEMBER_ID) references MEMBER (MEMBER_ID) ;

alter table GIANT_SIDE add constraint FK_GIANT_SIDE_ZONE_PURCHASE
	foreign key (ZONE_PURCHASE_ID) references PURCHASE (PURCHASE_ID) ;

alter table GIANT_SIDE add constraint FK_GIANT_SIDE_ZONE_PRODUCT
	foreign key (ZONE_PRODUCT_ID) references PRODUCT (PRODUCT_ID) ;


--
-- GIANT index
--
create index IX_GIANT_INDEX_STRING on GIANT (INDEX_STRING) ;
create index IX_GIANT_INDEX_INTEGER on GIANT (INDEX_INTEGER) ;
create index IX_GIANT_INDEX_DATE on GIANT (INDEX_DATE) ;
create index IX_GIANT_INDEX_DATETIME on GIANT (INDEX_DATETIME) ;
create index IX_GIANT_INDEX_BOOLEAN on GIANT (INDEX_BOOLEAN) ;

create index IX_GIANT_NULLABLE_INDEX_STRING on GIANT (NULLABLE_INDEX_STRING) ;
create index IX_GIANT_NULLABLE_INDEX_INTEGER on GIANT (NULLABLE_INDEX_INTEGER) ;
create index IX_GIANT_NULLABLE_INDEX_DATE on GIANT (NULLABLE_INDEX_DATE) ;
create index IX_GIANT_NULLABLE_INDEX_DATETIME on GIANT (NULLABLE_INDEX_DATETIME) ;
create index IX_GIANT_NULLABLE_INDEX_BOOLEAN on GIANT (NULLABLE_INDEX_BOOLEAN) ;

create index IX_GIANT_UNIQUE_2ND_INTEGER on GIANT (UNIQUE_2ND_INTEGER) ;
create index IX_GIANT_UNIQUE_4TH_INTEGER on GIANT (UNIQUE_4TH_INTEGER) ;


--
-- GIANT_REF index
--
create index IX_GIANT_REF_INDEX_STRING on GIANT_REF (INDEX_STRING) ;
create index IX_GIANT_REF_INDEX_INTEGER on GIANT_REF (INDEX_INTEGER) ;
create index IX_GIANT_REF_INDEX_DATE on GIANT_REF (INDEX_DATE) ;
create index IX_GIANT_REF_INDEX_DATETIME on GIANT_REF (INDEX_DATETIME) ;
create index IX_GIANT_REF_INDEX_BOOLEAN on GIANT_REF (INDEX_BOOLEAN) ;

create index IX_GIANT_REF_NULLABLE_INDEX_STRING on GIANT_REF (NULLABLE_INDEX_STRING) ;
create index IX_GIANT_REF_NULLABLE_INDEX_INTEGER on GIANT_REF (NULLABLE_INDEX_INTEGER) ;
create index IX_GIANT_REF_NULLABLE_INDEX_DATE on GIANT_REF (NULLABLE_INDEX_DATE) ;
create index IX_GIANT_REF_NULLABLE_INDEX_DATETIME on GIANT_REF (NULLABLE_INDEX_DATETIME) ;
create index IX_GIANT_REF_NULLABLE_INDEX_BOOLEAN on GIANT_REF (NULLABLE_INDEX_BOOLEAN) ;

create index IX_GIANT_REF_UNIQUE_2ND_INTEGER on GIANT_REF (UNIQUE_2ND_INTEGER) ;
create index IX_GIANT_REF_UNIQUE_4TH_INTEGER on GIANT_REF (UNIQUE_4TH_INTEGER) ;

create index IX_GIANT_REF_COMPOUND_GIANT_ID_INTEGER on GIANT_REF (GIANT_ID, INDEX_INTEGER) ;


--
-- GIANT_SIDE index
--
create index IX_GIANT_SIDE_INDEX_STRING on GIANT_SIDE (INDEX_STRING) ;
create index IX_GIANT_SIDE_INDEX_INTEGER on GIANT_SIDE (INDEX_INTEGER) ;
create index IX_GIANT_SIDE_INDEX_DATE on GIANT_SIDE (INDEX_DATE) ;
create index IX_GIANT_SIDE_INDEX_DATETIME on GIANT_SIDE (INDEX_DATETIME) ;
create index IX_GIANT_SIDE_INDEX_BOOLEAN on GIANT_SIDE (INDEX_BOOLEAN) ;

create index IX_GIANT_SIDE_NULLABLE_INDEX_STRING on GIANT_SIDE (NULLABLE_INDEX_STRING) ;
create index IX_GIANT_SIDE_NULLABLE_INDEX_INTEGER on GIANT_SIDE (NULLABLE_INDEX_INTEGER) ;
create index IX_GIANT_SIDE_NULLABLE_INDEX_DATE on GIANT_SIDE (NULLABLE_INDEX_DATE) ;
create index IX_GIANT_SIDE_NULLABLE_INDEX_DATETIME on GIANT_SIDE (NULLABLE_INDEX_DATETIME) ;
create index IX_GIANT_SIDE_NULLABLE_INDEX_BOOLEAN on GIANT_SIDE (NULLABLE_INDEX_BOOLEAN) ;

create index IX_GIANT_SIDE_UNIQUE_2ND_INTEGER on GIANT_SIDE (UNIQUE_2ND_INTEGER) ;
create index IX_GIANT_SIDE_UNIQUE_4TH_INTEGER on GIANT_SIDE (UNIQUE_4TH_INTEGER) ;

create index IX_GIANT_SIDE_COMPOUND_GIANT_ID_INTEGER on GIANT_SIDE (GIANT_ID, INDEX_INTEGER) ;


